---
title: "Data Management: Example Slides"
author: Grace Tompkins
format: 
  revealjs:
    theme: simple
    smaller: true
bibliography: ../../../bibliography/ISDSE.bib
---

## Data Management

<br>

-   Data management refers to the way that data is *collected*, *used*, and *stored*.

-   In many cases, data contains sensitive information, such as personal identifying information (PII) like names, addresses, and birth dates, or sensitive health-related data.

-   Data involving PII should be:

    -   Encrypted
    -   Only accessible by authorized users
    -   Anonymized (where possible)
    -   Used on a "need-to-know" basis

## Indigenous Data

-   Caution should be exercised when managing data on Indigenous Peoples and their lands.

-   To many, data may be seen through a **colonial** context as something that, too, has been **taken** [@rodriguez_2016].

    -   **Colonization**: the act of settling among and establishing control over Indigenous land and Peoples

-   Data on Indigenous Peoples has also been used as a weapon against them to gain **control** over them by colonial settlers.

## Indigenous Data: IDS

-   **Indigenous Data Sovereignty (IDS)**:the idea that Indigenous Peoples have the right to own and control how their data are collected, managed and used [@andersen_2025].

    -   Stems from Indigenous demands for the rights to their own data, and the harmful misuse of existing Indigenous data [@andersen_2025].

-   IDS is particularly relevant in the age of "open data", where issues relating to data consent, use, ownership, and storage have increased in complexity [@kukutai_2016].



## IDS in First Nations Communities

-   In Canada, the OCAP®  (*ownership, control, access, posession*) principles are established for First Nations to assert data sovereignty. 

::: incremental
-   **Ownership** refers to the relationship of First Nations to their cultural knowledge, data, and information.

-   **Control** affirms that First Nations, their communities, and representative bodies are within their rights to seek control over all aspects of research and information management processes that impact them. 

-   **Access** refers to the fact that First Nations must have access to information and data about themselves and their communities regardless of where it is held. 

-   **Possession** is the mechanism by which ownership can be asserted and protected.
:::

*Note: OCAP® is an expression of First Nations' jurisdiction over information about their communities. The principals of OCAP® are not an expression of all Indigenous communities.*


## Asserting OCAP with Data Sharing Agreements

A **data sharing agreement** is a formal contract which ensures Indigenous Peoples are prioritized while working in partnership with non-Indigenous organizations (for example, researchers, universities, private organizations, or government).

-    may involve a **data steward** who is responsible for receiving and maintaining the data under the agreement

Some considerations for agreements:

::: incremental
- Who are the parties involved?
- What type of data is being collected/stored/used? Which data will be shared?
- What is the scope? Is this a one-time or a continued collection/storage/usage?
- Who is the data steward? 
- When will the agreement be terminated?
:::


## Data on Indigenous Peoples: Discussion

-   Why might Indigenous Peoples want control over how their data is collected, stored, and used? Discuss in small groups.

::: incremental
-   Possible Answer:
    -   *While data can be used in a beneficial way for Indigenous communities, analyses using data on Indigenous Peoples often present with uncontrolled for biases as a result of colonization and a lack of understanding of Indigenous Peoples* [@kukutai_2016].
    -   *Such biases can be harmful to Indigenous Peoples*.
:::

## Reflection Activity

Read [this article](https://globalnews.ca/news/10318288/pictou-landing-first-nation-accuse-radiologists-secret-tests/) involving members of Pictou Landing First Nation in Nova Scotia, Canada. The Mi'kmaq are the Indigenous Peoples who are native to Nova Scotia, New Brunswick, PEI, Newfoundland, and parts of Quebec and Maine. 

Prepare to discuss the following questions in a small group:
- Was the researcher respecting the principles of OCAP throughout this study?
- Is it really a big deal if extra "non-invasive" scans were taken? 

## Continue the Lecture!

*(Continue talking about Data Management as you would in a typical offering of your course, connecting back to the principals of IDS where appropriate.)*

## References



