---
title: "Data Management: Example Slides"
author: Grace Tompkins
format: 
  revealjs:
    theme: simple
    smaller: true
bibliography: ../../../../ISDSE.bib
bibliographystyle: apa
---

## Data Management

<br>

-   Data management refers to the way that data is *collected*, *used*, and *stored*.

-   In many cases, data contains sensitive information, such as personal identifying information (PII) like names, addresses, and birth dates, or sensitive health-related data.

-   Data involving PII should be:

    -   Encrypted
    -   Only accessible by authorized users
    -   Anonymized (where possible)
    -   Used on a "need-to-know" basis

## Data on Indigenous Peoples

-   Caution should be exercised when managing data on Indigenous Peoples.

-   To many, data may be seen through a **colonial** context as something that, too, has been **taken** [@rodriguez_2016].

    -   **Colonization**: the act of settling among and establishing control over Indigenous land and Peoples

-   Data on Indigenous Peoples has also been used as a weapon against them to gain **control** over them by colonial settlers.

## Data on Indigenous Peoples: IDS

-   **Indigenous Data Sovereignty (IDS)**:the idea that Indigenous Peoples have the right to own and control how their data are collected, managed and used [@andersen_2025].

    -   Stems from Indigenous demands for the rights to their own data, and the harmful misuse of existing Indigenous data [@andersen_2025].

-   IDS is particularly relevant in the age of "open data", where issues relating to data consent, use, ownership, and storage have increased in complexity [@kukutai_2016].

## Data on Indigenous Peoples: Discussion

-   Why might Indigenous Peoples want control over how their data is collected, stored, and used? Discuss in small groups.

::: incremental
-   Possible Answer:
    -   *While data can be used in a beneficial way for Indigenous communities, analyses using data on Indigenous Peoples often present with uncontrolled for biases as a result of colonization and a lack of understanding of Indigenous Peoples* [@kukutai_2016].
    -   *Such biases can be harmful to Indigenous Peoples*.
:::

## Continue the Lecture!

*(Continue talking about Data Management as you would in a typical offering of your course.)*

## References
